[package]
authors.workspace = true
categories = ["encoding"]
description = "Pilota is a thrift and protobuf implementation in pure rust with high performance and extensibility."
documentation = "https://docs.rs/pilota"
edition.workspace = true
homepage.workspace = true
keywords = ["serialization", "thrift", "protobuf"]
license.workspace = true
name = "pilota"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.13.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
maintenance = {status = "actively-developed"}

[dependencies]
ahash = {workspace = true, features = ["serde"]}
anyhow.workspace = true
async-recursion.workspace = true
bytes.workspace = true
faststr = {workspace = true, features = ["serde"]}
integer-encoding.workspace = true
lazy_static.workspace = true
linkedbytes.workspace = true
ordered-float.workspace = true
paste.workspace = true
protobuf.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
rand.workspace = true

[features]
no-recursion-limit = []
pb-encode-default-value = []
unstable = []

[[bench]]
harness = false
name = "faststr"

[[bench]]
harness = false
name = "thrift_binary"

[[bench]]
harness = false
name = "skip"

[[bench]]
harness = false
name = "ttype"

[[bench]]
harness = false
name = "pb"
